version: '3'
services:
  wordpress:
    image: wordpress:5.7.1
    ports:
      - 4000:80
    restart: always
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: secret
      WORDPRESS_DB_NAME: wp_db
      WORDPRESS_DB_HOSTNAME: db
      WORDPRESS_DB_CHARSET: utf8mb4
      WORDPRESS_DB_COLLATE: utf8mb4_unicode_ci
    volumes:
      - wordpress:/var/www/html

  db:
    image: mysql:5.7
    restart: always
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 5s
      retries: 3
    environment:
      MYSQL_DATABASE: wp_db
      MYSQL_USER: user
      MYSQL_PASSWORD: secret
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
    volumes:
      - db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.4
    ports:
      - 4001:80
    restart: always
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
    volumes:
      - phpmyadmin:/sessions

  nginx:
    image: nginx
    network_mode: host
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
  
  node-exporter:
    image: prom/node-exporter:v1.2.2
    restart: always
    ports:
      - 9100:9100

  prometheus:
    image: prom/prometheus:v2.30.3
    restart: always
    ports:
      - 9090:9090
    volumes:
      - ./prometheus:/etc/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana:8.2.0
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      GF_INSTALL_PLUGINS: grafana-clock-panel

volumes:
  wordpress:
  db:
  phpmyadmin:
